eclipse-syson/syson

- .vscode/settings.json
- CHANGELOG.adoc
- backend/application/syson-application-configuration/.classpath
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/StereotypeDescriptionRegistryConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLStandardLibrariesConfiguration.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2ProjectTemplatesInitializer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessorTest.java
- backend/metamodel/syson-sysml-metamodel/pom.xml
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/LibraryPackageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/RelationshipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SysmlFactoryImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/SysmlResourceFactoryImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/SysmlResourceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/resources/model/sysml.genmodel
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/metamodel/ElementUtilTest.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
First part of the support for standard libraries.
The real libraries should be added in a future PR.
> [52] Support for standard libraries

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetIntermediateContainerCreationSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewCreateService.java
Bug: https://github.com/eclipse-syson/syson/issues/78
> [78] Review new objects candidates in Explorer view context menu

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/MetadataUsageItemProvider.java
- backend/metamodel/syson-sysml-metamodel-edit/src/main/resources/icons/full/obj16/MetadataUsage.svg
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/EmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewNodeDescriptionProviderSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/PackageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UsageNodeDescriptionProvider.java
Adding 3 incomplete sections:
- Structure
- Interconnection
- Extension
> [93] Refactor General View diagram palette

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/SysONEContentAdapter.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubsettingEdgeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/112
> [112] Improves getAllReachable util service

- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewJavaServiceProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/PackageNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractFeatureTypingEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractRedefinitionEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubclassificationEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubsettingEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractDefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractFakeNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewJavaServiceProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/PackageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- Definition node description
- Usage node description
- Package node description
- Fake node description
- Tool services
Bug: https://github.com/eclipse-syson/syson/issues/93
> [93] Reorganize existing diagram modules to share common behaviors

- backend/metamodel/syson-sysml-metamodel-edit/src/main/resources/icons/full/obj16/Subject.svg
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/RequirementConstraintMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/RequirementUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SubjectMembershipImpl.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/IDescriptionNameGenerator.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/CompartmentNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GVDescriptionNameGenerator.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewNodeDescriptionProviderSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/RVDescriptionNameGenerator.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/RequirementViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/RequirementSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/services/RequirementViewNodeToolSectionSwitch.java
> [93] Handle RequirementUsage and RequirementDefinition in Requirement View

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/DependencyEdgeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/134
> [134] Add FeatureTyping Edge tool

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/RequirementSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractCompartmentNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/RequirementSubjectCompartmentNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/services/RequirementViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/93
> [93] Handle DnD of RequirementUsage subjects

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/CompartmentNodeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/93
> [93] Fix DnD Constraints into different Constraint compartments

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
Bug: https://github.com/eclipse-syson/syson/issues/137
> [137] Add RequirementConstraintMembership#kind on constraint properties

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLStandardLibrariesConfiguration.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/AbstractViewElementDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/diagram/AbstractDiagramDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPartUsageNodeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/144
> [144] Fix Add existing elements tool recursive on PartUsage

- backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/ElementItemProvider.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/Element.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AllocationDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AllocationUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AttributeDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AttributeUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/DataTypeImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/DocumentationImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/EnumerationDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/EnumerationUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/InterfaceDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/InterfaceUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ItemDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ItemUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MembershipImportImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImportImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/OwningMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PackageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PartDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PartUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PerformActionUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PortDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PortUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ReferenceUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/VariantMembershipImpl.java
Bug: https://github.com/eclipse-syson/syson/issues/140
> [140] Fix TextualReprestation creation

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AttributeUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ReferenceUsageImpl.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/UsageNestedUsageEdgeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/153
> [153] Forbid composite usages inside PortDefinition/PortUsage

- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/151
Bug: https://github.com/eclipse-syson/syson/issues/154
> [151, 154] Add composite usage of Requirement in Requirement

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/SubclassificationEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/SubclassificationEdgeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewNodeDescriptionProviderSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/165
> [165] OccurrenceDefinition and OccurrenceUsage in General View diagram

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildrenPartUsageCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewLabelService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/ChildrenPartUsageCompartmentNodeToolProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/167
> [167] Add attributes compartment in children PartUsage in IV

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractFeatureTypingEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractRedefinitionEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubclassificationEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubsettingEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/DefinitionOwnedUsageEdgeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/177
> [177] Add missing reconnect tools for composition edges

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeService.java
An example of such chained allocate edge can be found in: SysML-v2-Release/sysml/src/examples/Simple Tests/AllocationTest.sysml
Bug: https://github.com/eclipse-syson/syson/issues/180
> [180] support chained allocate edge ends

- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ParentNodeFinder.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewJavaServiceProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/AllocateEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewEdgeService.java
Bug: https://github.com/eclipse-syson/syson/issues/180
> [180] Allow allocate edges between usages

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/209
> [209] EnumerationDefinition is created without any name

- CHANGELOG.adoc
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/ChildrenPartUsageCompartmentNodeToolProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/183
> [183] Expand nodes in diagrams when a compartment item is created

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/InterfaceUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewEdgeService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewLabelService.java
Bug: https://github.com/eclipse-syson/syson/issues/234
> [234] Handle Interface edges in InterconnectionView

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/DefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/DescriptionNameGenerator.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/IDescriptionNameGenerator.java
- backend/tests/syson-tests/src/test/java/org/eclipse/syson/tests/GitCommitMessageTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/InheritedCompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/InheritedCompartmentItemFilterSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewJavaServiceProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewEdgeService.java
Bug: https://github.com/eclipse-syson/syson/issues/242
> [242] Handle Inherited features in features compartments

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
Bug: #249
Signed-off-by: Guillaume Escande <guillaume.escande@obeosoft.fr>
> [249] Fix infinite Loop

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/mapper/MapperNamespaceImport.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/mapper/MappingElement.java
Bug: https://github.com/eclipse-syson/syson/issues/262
> [262] Fix NPE while importing standard examples

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractDefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/CompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/InheritedCompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/BindingConnectorAsUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/InterfaceUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/264
> [264] Restore hide capabilities

- CHANGELOG.adoc
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/NameConflictingFilter.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/NamespaceImplTest.java
Bug: https://github.com/eclipse-syson/syson/issues/274
> [274] Prevent name conflict while importing elements

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
Fix hidden default state for single value compartments
> [268] Reveal the appropriate compartment when creating child elements

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForDefinitionDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForDefinitionDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForUsageDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForUsageDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewJavaServiceProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/AllocateEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/BindingConnectorAsUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/InterfaceUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildrenPartUsageCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FirstLevelChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootDefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewEdgeService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewLabelService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/278
> [278]Allow to create Interconnection View on any Usage/Definition

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/pom.xml
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/NameHelper.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/OwningMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/NamespaceImplTest.java
Implement some metamodel methods :
-  resolve methods of metamodel for Namespace Object
- getMemberName and get MemberShortName using directly member value instead of local value
> [enh] implement metamodel resolve methods

- CHANGELOG.adoc
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewJavaServiceProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeService.java
- backend/views/syson-diagram-interconnection-view/src/main/resources/images/PortUsage_In.svg
- backend/views/syson-diagram-interconnection-view/src/main/resources/images/PortUsage_InOut.svg
- backend/views/syson-diagram-interconnection-view/src/main/resources/images/PortUsage_Out.svg
Bug: https://github.com/eclipse-syson/syson/issues/285
> [285] Add rotative images for PortUsage in Interconnection View

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
Bug: https://github.com/eclipse-syson/syson/issues/271
> [271] Remove non end Usages from AllocationDefinition ends compartment

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/229
> [229] Prevent self containment as nested part

- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/277
> [fix] Nested actions are missing in free-form when Add existing elements

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/AQLUtils.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewEdgeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewEdgeService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewEdgeService.java
Bug: https://github.com/eclipse-syson/syson/issues/297
> [297] Handle Succession edge in diagrams

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/AbstractViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionObjectiveRequirementCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageObjectiveRequirementCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/edges/TransitionEdgeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/PackageNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionViewEmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/308
> [308] Clean up State Transition View code

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDefinitionOwnedUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/254
> [254] Add delete from model tool on containment edges

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/InheritedCompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
Bug: https://github.com/eclipse-syson/syson/issues/294
> [294] Inherited features in compartments should not display itself

- CHANGELOG.adoc
- backend/application/syson-sysml-export/pom.xml
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Appender.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/NameHelper.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ElementTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/NamespaceImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/TypeImplTest.java
Bug : https://github.com/eclipse-syson/syson/issues/298
Signed-off-by: Guillaume Escande <guillaume.escande@obeosoft.fr>
> Correct metamodel to manage root namespace

- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
Correct import code to manage the root empty namespace
> [298] Import root namespace

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLRelationPredicates.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Appender.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/MembershipComputer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/DefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MembershipImportImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImportImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/OwningMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/NamespaceImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PartDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PartUsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/TypeImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/TestUtils.java
This commit also bring some performance improvements to handle big model.
> [196] Improve NameDeresolver to handle name conflicts

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/AQLUtils.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StartActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StartActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/resources/icons/done_action.svg
- backend/views/syson-diagram-common-view/src/main/resources/icons/start_action.svg
- backend/views/syson-diagram-common-view/src/main/resources/images/done_action.svg
- backend/views/syson-diagram-common-view/src/main/resources/images/start_action.svg
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPortUsageBorderNodeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/269
> [269] Handle start action in AFV

- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
The only Handle start action in GV commit has to be reviewed.
Once PR [[269] Handle start action in AFV](https://github.com/eclipse-syson/syson/pull/335) is merged this PR will rebased.
> [269] Handle start action in GV

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Appender.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/AttributeUsageWithBinaryOperatorExpressionTestModel.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/AttributeUsageWithBracketOperatorExpressionTestModel.java
Bug:https://github.com/eclipse-syson/syson/issues/196
> [196] Partial implementation of Expression while exporting as textual files

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConjugatedPortDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/LifeClassImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ReferenceUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConjugatedPortDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/FeatureImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/UsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
Bug: https://github.com/eclipse-syson/syson/issues/344
> [344] Implement effectiveName for SysML and KerML elements

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/DoneActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/DoneActionNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/SuccessionEdgeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/DefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UsageNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/269
> [269] Handle standard done action in both AFV and GV diagrams

- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PartUsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/UsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
Bug: https://github.com/eclipse-syson/syson/issues/344
> [344] Fix implementation of effectiveName for Usage

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Appender.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/AttributeUsageWithFeatureChainExpressionTestModel.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/AttributeUsageWithSequenceExpressionTestModel.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureChainingImpl.java
Implementation of FeatureChainExpression and more OperatorExpression variant
> [196] Partial implementation of Expression in export to textual files

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/269
> [fix] Avoid creation of Dependency edge tool Start and Done actions

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
> [196] Implement export of PartUsage

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
Covering more ClassificationExpression cases
> [196] Handling more OperatorExpression in export to textual files

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLV2DocumentExporter.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Severity.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Status.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLModelToTextSwitchTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/DeresolvingNamespaceProvider.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ReferenceSubsettingImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConjugatedPortDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConstraintUsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/FeatureImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/NamespaceImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PartDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PerformActionUsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/TypeImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/UsageImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
> [196] Handle ActionDefinition, ActionUsage and SuccessionAsUsage

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- Add source and target derived structural features in core properties for a Transition
- Code refactorings
Bug: https://github.com/eclipse-syson/syson/issues/388
> [388] Transition source and target in core properties

- CHANGELOG.adoc
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StartActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractFreeFormCompartmentNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AcceptActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/DecisionActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/DoneActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ForkActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/MergeActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StartActionNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/391
> [391] AcceptAction should be available inside an Action body

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConjugatedPortDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/IncludeUseCaseUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MetadataUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ReferenceSubsettingImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/StateSubactionMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TransitionFeatureMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/UsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConjugatedPortDefinitionImplTest.java
Bug: https://github.com/eclipse-syson/syson/issues/394
> [394] Fix some minor issue with redefine feature

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractControlNodeActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StartActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/403
> [403] Wrong computation of the succession owner

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
Bug: https://github.com/eclipse-syson/syson/issues/407
> [407] Fix the owner membership of dropped elements

- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
> [196] Align test class name with tested class

- CHANGELOG.adoc
- backend/application/syson-application/src/main/resources/application.properties
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/SysmlToAst.java
Bug: https://github.com/eclipse-syson/syson/issues/416
> [416] Improve textual import running process

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/InterfaceDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/InterfaceDefinitionImplTest.java
> [196] Handle InterfaceDefinition and PortUsage

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/ConditionalBinaryOperatorExpressionTestModel.java
Implementation of ConditionalBinaryOperatorExpression
> [196] Handle more OperatorExpression in export to textual files

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
> [196] Implementation of RequirementDefinition in export to textual files

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
> [196] Implementation of MetadataDefinition in export to textual files

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/ConstraintUsageWithOperatorExpressionTestModel.java
> [196] Implementation of ConstraintUsage in export to textual files

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/NodeDescriptionService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
Bug: https://github.com/eclipse-syson/syson/issues/445
> [445] Improve the way node descriptions are retrieved for a given semantic element

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
> [196] Implementation of RequirementUsage in export to textual files

- .github/workflows/doc-gen.yml
- doc/content/modules/developer-guide/pages/extend.adoc
- doc/content/modules/installation-guide/pages/how-tos/install.adoc
- doc/content/modules/installation-guide/pages/troubleshooting.adoc
- doc/content/modules/user-manual/pages/contribute.adoc
- doc/content/modules/user-manual/pages/cycle.adoc
- doc/content/modules/user-manual/pages/faq/faq.adoc
- doc/content/modules/user-manual/pages/integration/extend.adoc
- doc/content/modules/user-manual/partials/nav-integration.adoc
Contribute to troubleshooting.adoc
Add missing information in extend.adoc and contribute.adoc pages 
Remove duplicated extend.adoc file
Update application start command line argument in install.adoc
> [doc] Different fixes in documentation

- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
> [196] Implementation of ReferenceUsage in export to textual files

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- integration-tests/cypress/e2e/project/details/details.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/460
> [460] Always display "Typed by" extra properties in Details view

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
Bug:https://github.com/eclipse-syson/syson/issues/472
> [472] Move Feature#direction in Core tab of the Details view

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
Bug: https://github.com/eclipse-syson/syson/issues/475
> [475] Sort New Object menu entries

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/DoneActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StartActionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/DoneActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StartActionNodeToolProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/479
> [479] Allow multiple Start and Done actions in action body

- doc/Dockerfile
- doc/docs-site/antora-playbook.yml
- upgrade doc generation to manage edit_url 
- upgrade doc generation to manage multiple tags
> [enh] upgrade doc generation to manage edit_url and multiple tags

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/483
> [483] Do not display empty/null relationships in diagram node labels

- CHANGELOG.adoc
- frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Bug: https://github.com/eclipse-syson/syson/issues/490
> [490] Adjust size tool has no effect on Package nodes

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ExhibitStatesCompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/AbstractViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/CompartmentNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForDefinitionDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewForUsageDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FirstLevelChildPartUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootDefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/482
> [482] Add tools for creating Ports with direction

- CHANGELOG.adoc
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/492
> [492] Add tools for creating Items with direction in all diagrams

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetIntermediateContainerCreationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/NameHelper.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/helper/NameHelperTest.java
Bug: https://github.com/eclipse-syson/syson/issues/502
> [502] Escaped simple quotes when exporting as textual files

- CHANGELOG.adoc
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
Bug: https://github.com/eclipse-syson/syson/issues/511
> [511] Fix global indentation for export as textual files

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/501
> [501] Remove quotes when set string value through direct edit

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildrenPartUsageCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionCompartmentNodeDescriptionProvider.java
Avoid arrange all to mask the compartments titles
> [fix] Fix free form compartments header value in diagrams

- CHANGELOG.adoc
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/AbstractViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateTransitionActionCompartmentToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/AllocationDefinitionEndsCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionObjectiveRequirementCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageObjectiveRequirementCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildrenPartUsageCompartmentNodeDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/492
> [492] Add missing tools for creating Items and Ports with direction

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
Bug: https://github.com/eclipse-syson/syson/issues/505
> [505] Add value expression in Node label

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeCreationTests.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/507
> [507] Add missing tools to create Items and Parts in Port

- .github/workflows/build.yml
Correct double build 
Add explicit registry in image name
> [releng] Correction for Replace the AWS registry by dockerhub registry

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
Bug: https://github.com/eclipse-syson/syson/issues/540
> [540] Allow the creation of sub-Packages in the model explorer

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/CompartmentItemNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StateTransitionCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/ActionItemNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
Bug: https://github.com/eclipse-syson/syson/issues/554
> [554] Add State in PartUsage and PartDefinition

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/JavaServiceIsCalledChecker.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewCreateService.java
This PR corresponds to the following issues:
- #557 
- #558
> Allow to create StateTransitionView diagram on States and Parts

- CHANGELOG.adoc
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
> [571] Add ActionUsage node in Interconnection View

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ExhibitStateNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/585
> [585] Add tool to create an ExhibitState at the root of diagrams

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/FlowConnectionUsageEdgeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPortUsageBorderNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/587
> [587] Handle flow between Ports in InterconnectionView

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/590
> [590] Add label support for referential Usages

- CHANGELOG.adoc
- backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/SetAsCompositeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/SetAsRefToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/598
> [598] Add tools to set a Feature as composite or reference

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/615
> [615] Add documentation property to details view

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/621
> [621] Fix non-containment reference issue on standard library copy

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/NodeCreationTester.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/services/diagrams/NodeCreationTestsService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractFreeFormCompartmentNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ReferencingPerformActionNodeToolProvider.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/624
> [624] Allow to select existing Action on Perform tool

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractCompartmentNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/SubjectCompartmentNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageSubjectCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/634
> [634] Allow to select existing Type on Subject tool

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/654
> [654] Prevent the drop of an element on one of its children

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/656
> [656] Improve drag and drop of containers to move their content

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
- backend/views/syson-diagram-common-view/src/test/java/org/eclipse/syson/diagram/common/view/services/ViewLabelServiceTest.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/658
> [658] Fix direct edit for Constraint and Requirement

- CHANGELOG.adoc
- backend/tests/syson-tests/src/test/java/org/eclipse/syson/tests/GeneralPurposeTests.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/662
> [662] Make the build fail when a Cypress test contains it.only

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
- integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/665
> [665] Support public imports in direct edit specializations

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/HideRootNamespaceTreeItemAlteredContentProvider.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysONTreeFilterProvider.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewCreateService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
- integration-tests/cypress/e2e/project/details/details.cy.ts
- integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
- integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
- integration-tests/cypress/e2e/project/explorer/semanticElementCreationTests.cy.ts
- integration-tests/cypress/workbench/Explorer.ts
Bug: https://github.com/eclipse-syson/syson/issues/671
> [671] Improve support of root Namespace

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
- integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
- integration-tests/cypress/workbench/Diagram.ts
- integration-tests/cypress/workbench/Workbench.ts
Bug: https://github.com/eclipse-syson/syson/issues/678
> [678] Ensure that dropping an element reveals its node if it exists.

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/DiagramDirectEditListenerTest.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/685
> [685] Fix name resolution in constraint expressions

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/705
> [705] Fix ConjugatedPortDefinition label

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FirstLevelChildUsageNodeDescriptionProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootNodeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/704
> [704] Fix direct edit for Interconnection View nodes

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
- integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/715
> [715] Fix the drop of an element on itself

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/UtilServiceTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/711
> [711] Prevent feature typing from disappearing when nesting part

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
- integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/722
> [722] Allow to drop any element on the diagram background

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstObjectParser.java
- backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertAssignmentTest/assignment2.ast.json
- doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/726
> [726]  Add support for isReference attribute in SysML parser

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/nodes/SysMLNoteNodeStyle.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/nodes/SysMLNoteNodeStyleProvider.java
- backend/application/syson-application-configuration/src/main/resources/schema/sysmlcustomnodes.graphqls
- backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/src/main/java/org/eclipse/syson/sysmlcustomnodes/provider/SysMLCustomnodesItemProviderAdapterFactory.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/src/main/java/org/eclipse/syson/sysmlcustomnodes/provider/SysMLNoteNodeStyleDescriptionItemProvider.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/src/main/resources/icons/full/obj16/SysMLNoteNodeStyleDescription.svg
- backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/src/main/resources/plugin.properties
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/SysMLCustomnodesFactory.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/SysMLCustomnodesPackage.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/SysMLNoteNodeStyleDescription.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/impl/SysMLCustomnodesFactoryImpl.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/impl/SysMLCustomnodesPackageImpl.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/impl/SysMLNoteNodeStyleDescriptionImpl.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/util/SysMLCustomnodesAdapterFactory.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/java/org/eclipse/syson/sysmlcustomnodes/util/SysMLCustomnodesSwitch.java
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/resources/model/sysml-customnodes.ecore
- backend/metamodel/syson-siriusweb-customnodes-metamodel/src/main/resources/model/sysml-customnodes.genmodel
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
- frontend/syson-components/src/index.ts
- frontend/syson-components/src/nodes/SysMLNodesDocumentTransform.ts
- frontend/syson-components/src/nodes/note/SysMLNoteNode.tsx
- frontend/syson-components/src/nodes/note/SysMLNoteNode.types.ts
- frontend/syson-components/src/nodes/note/SysMLNoteNodeConverter.ts
- frontend/syson-components/src/nodes/note/SysMLNoteNodeLayoutHandler.ts
- frontend/syson/src/index.tsx
Add a new custom node Note among possible node style descriptions.
Bug: https://github.com/eclipse-syson/syson/issues/694
> [694] Add custom node Note

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/697
Signed-off-by: Jessy Mallet <jessy.mallet@obeo.fr>
Be careful, before merging this PR, PR https://github.com/eclipse-syson/syson/pull/731 should be merged.
> [697] Add Comment property to details view

- CHANGELOG.adoc
- backend/application/syson-sysml-import/.classpath
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstTreeParser.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstWeakReferenceParser.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ProxiedReference.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ProxyResolver.java
- backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertFeatureTypingTest/model.ast.json
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertInheritanceTest/inheritance.ast.json
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertInheritanceTest/inheritance.sysml
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertNamespaceImportValueTest/model.ast.json
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertRedefinesTest/model.ast.json
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertVisibilityTest/model.ast.json
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Now resolve aliases and external references in tandem rather than successively.
> [717] Reworking file import

- integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
> [test] Update Cypress tests

- backend/tests/syson-tests/src/test/java/org/eclipse/syson/tests/GeneralPurposeTests.java
- docker-compose.yml
> [releng] Prepare next release

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/checkers/DiagramCheckerService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/EdgeCreationTester.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/ImplicitSpecializationsTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/services/diagrams/DiagramDescriptionIdProvider.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/services/diagrams/NodeCreationTestsService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/754
> [754] Add an edge tool to add target element as nested usage

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/LabelConstants.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/LabelServiceTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
- backend/views/syson-diagram-common-view/src/test/java/org/eclipse/syson/diagram/common/view/services/ViewLabelServiceTest.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/756
> [756] Add short name in container and compartment item labels

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewSubsettingFromPartUsageTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PartUsageSubsettingNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/779
> [779] Add new tool to create a full subsetting from Part Usage

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewSubsettingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/NodeCreationTester.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PartUsageFeatureTypingNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
>  [780] Add new tool to create a full FeatureTyping from PartUsage 

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstObjectParser.java
- backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertBooleanTest/model.ast.json
- backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertBooleanTest/model.sysml
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
* isAbstract
* isDerived
* isEnd
* isReadOnly
Bug: https://github.com/eclipse-syson/syson/issues/777
Signed-off-by: Étienne Bausson <etienne.bausson@obeosoft.com>
> [777] Handle boolean attributes recognized as string by the import parser.

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewFlowConnectionFromPartUsageTests.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/ChildUsageCreationNodeToolsProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/FirstLevelChildUsageCreationNodeToolsProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeToolSectionSwitch.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/PartUsageFlowConnectionNodeToolProvider.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [789] Add New Flow Connection tool on PartUsage in IV

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/ChildUsageCreationNodeToolsProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/FirstLevelChildUsageCreationNodeToolsProvider.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/PartUsageInterfaceNodeToolProvider.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [790] Add New Interface tool on PartUsage in IV

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/pom.xml
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [releng] Switch to java-uuid-generator 5.1.0

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/UseCaseDefinitionTestModel.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ProxyResolver.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/DeresolvingNamespaceProvider.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [795] Fix name resolution of implicit redefining feature

- CHANGELOG.adoc
- doc/content/modules/developer-guide/pages/index.adoc
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/810
> [810] Update SysIDE dependency to 0.6.2

- .github/workflows/build.yml
- backend/application/syson-application-configuration/pom.xml
- backend/application/syson-sysml-export/pom.xml
- backend/application/syson-sysml-import/pom.xml
- backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
- backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
- backend/metamodel/syson-sysml-metamodel-edit/pom.xml
- backend/metamodel/syson-sysml-metamodel/pom.xml
- backend/releng/pom.xml
- backend/releng/syson-test-coverage/.project
- backend/releng/syson-test-coverage/pom.xml
- backend/services/syson-direct-edit-grammar/pom.xml
- backend/services/syson-services/pom.xml
- backend/views/syson-diagram-actionflow-view/pom.xml
- backend/views/syson-diagram-common-view/pom.xml
- backend/views/syson-diagram-general-view/pom.xml
- backend/views/syson-diagram-interconnection-view/pom.xml
- backend/views/syson-diagram-statetransition-view/pom.xml
- pom.xml
- scripts/check-coverage.jsh
> [releng] Add code coverage check on backend

- .github/workflows/build.yml
- .github/workflows/doc-gen.yml
- .github/workflows/pull-request.yml
> [releng] Update github actions versions in workflows

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
- integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/812
> [812] Fixing import visibility in Deresolver

- .github/workflows/build.yml
- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/sample/CameraModel.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/sample/ItemTest.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/sample/PictureTakingModel.java
- backend/views/syson-diagram-interconnection-view/pom.xml
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewCreateServiceTests.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [817] Fix InterfaceUsage and FlowConnectionUsage creation services

- LICENSE-LGPL
Bug: https://github.com/eclipse-syson/syson/issues/822
> [releng] Fix LICENSE-LGPL content

- .github/workflows/pull-request.yml
- scripts/check-changelog.js
> [releng] Add documentation changelog check in workflow build

- doc/content/modules/user-manual/pages/integration/api.adoc
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
- scripts/check-coverage.jsh
> [test] Update expected code coverage levels

- doc/content/modules/user-manual/pages/integration/api.adoc
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
- integration-tests/cypress/e2e/project/details/details.cy.ts
> [doc] Fix doc

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/DiagramDirectEditListenerTest.java
- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
- frontend/syson-components/src/nodes/note/SysMLNoteNode.tsx
- frontend/syson-components/src/nodes/package/SysMLPackageNode.tsx
> [836] Fix the deletion of the cardinality of a Usage through direct edit

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/explorer/DropTreeItemHandler.java
> [fix] Disable D&D of TreeItems inside Explorer view

- doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
> [doc] Update release note highlights

- CHANGELOG.adoc
- backend/application/syson-application/src/test/resources/simple_project.json
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/OccurrenceUsage.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/OccurrenceUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SysmlPackageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/resources/model/sysml.ecore
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
* was snapshot, changed to null.
* same thing for ConnectionUsage, which is a subclass of OccurrenceUsage, but java doesn't allow multiple inheritance.
Bug: https://github.com/eclipse-syson/syson/issues/829
- [ X] Has the `CHANGELOG.adoc` + `doc/content/modules/user-manual/pages/release-notes/YYYY.MM.0.adoc` been updated to reference the relevant issues?
> [829] Metamodel change to OccurrenceUsage's PortionKind cardinality and default value

- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/802
> [802] Include ImportNamespace elements with Add Existing elements tool

- integration-tests/cypress/workbench/Explorer.ts
> [test] Fix shaky cypress test

- doc/content/modules/installation-guide/pages/requirements.adoc
> [doc] Update requirements with Node.js

- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
> [cleanup] Typos & code quality fixes.

- integration-tests/cypress/e2e/project/details/details.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/addExistingElements.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/diagramPanelTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
- integration-tests/cypress/workbench/Diagram.ts
> [test] Remove some arbitrary wait instructions in cypress tests

- backend/application/syson-application/Dockerfile
> [releng] Dockerfile structure upgrade to be based on temurin

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
> [818] Support of Occurence export.

- CHANGELOG.adoc
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/868
> [868] Fix textual export of LibraryPackage

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/883
> [883] Fix `getChildren` explorer error with specific filter combinations

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysONIdentityService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/relatedelements/view/RelatedElementsViewTests.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/884
> [884] Fix Related Elements View errors on implicit Specializations

- CHANGELOG.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
- frontend/syson-components/src/extensions/InsertTextualSysMLv2MenuContribution.tsx
Bug: https://github.com/eclipse-syson/syson/issues/888
> [888] Remove 'New objects from text' tool for libraries in the explorer

- CHANGELOG.adoc
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/UserLibrariesDirectory.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/895
> [895] Fix deletion of imported models from the explorer

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/upload/SysMLExternalResourceLoaderService.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/901
> [901] Allow to import .kerml files

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/objects/ObjectCreationTests.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/upload/SysMLExternalResourceLoaderService.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
- doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/906
> [906] Ensure that imported non-library models are not in user libraries

- doc/content/modules/user-manual/pages/integration/api.adoc
> [doc] Update APIs doc

- doc/content/modules/installation-guide/pages/how-tos/https.adoc
- doc/content/modules/installation-guide/pages/how-tos/install.adoc
- doc/content/modules/installation-guide/pages/how-tos/install/ecosystem_only.adoc
- doc/content/modules/installation-guide/pages/how-tos/install/local_test.adoc
- doc/content/modules/installation-guide/pages/how-tos/install/multi_user_test.adoc
- doc/content/modules/installation-guide/pages/how-tos/install/production_deploy.adoc
> [doc]  Fix content and linter issues in installation guide 

- doc/content/modules/user-manual/pages/cycle.adoc
> [doc] Fix content of the user manual cycle page

- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
This is preliminary work for #897 and #899 which will contribute to the General View.
This PR groups the non-functional changes that came up during development.
> [cleanup] Miscellaneous improvements around 'General View' DiagramDescription

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/941
> [941] Prevent edition of imported user libraries from the details view

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessorTest.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/SysONExplorerContributionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/943
> [943] Use Sirius Web's default explorer for studio projects

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/rest/RestControllerIntegrationTests.java
- backend/services/syson-sysml-rest-api-services/pom.xml
- backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2SerializerConfig.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/953
> [953] Fix server crash when successive REST APIs calls are executed

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewBindingConnectorAsUsageFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewFlowConnectionFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/NodeCreationTester.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/ElementInitializerSwitchTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
- backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewCreateServiceTests.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
- integration-tests/cypress/e2e/project/details/details.cy.ts
- integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
- integration-tests/cypress/e2e/project/explorer/semanticElementCreationTests.cy.ts
- integration-tests/cypress/workbench/Explorer.ts
Bug: https://github.com/eclipse-syson/syson/issues/961
> [961] Add valid default names for Elements

- doc/content/modules/user-manual/pages/faq/faq.adoc
> [doc] Contribute new question in FAQ about the project name

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/projects/ProjectDataVersioningRestControllerIntegrationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/services/SysMLReadOnlyServiceTest.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLMoveElementService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLReadOnlyService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/ISysMLMoveElementService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/ISysMLReadOnlyService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/MoveStatus.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/SysMLMoveElementServiceTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandler.java
- doc/content/modules/user-manual/pages/features/explorer.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/987
> [987] Implementation of DnD in SysOn Explorer view

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLStandardLibrariesConfiguration.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2RewriteProxiesResourcesFilter.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessorTest.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLv2EditingContextPersistenceFilter.java
- backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/ElementItemProvider.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/metamodel/ElementUtilTest.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLReadOnlyService.java
- backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysONObjectRestService.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerFilterService.java
- backend/views/syson-tree-explorer-view/src/test/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerFilterServiceTest.java
> [cleanup] Move kermllibrary and sysmllibrary constants to ElementUtils

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/992
> [992] Export Concern and Stakeholder concepts

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/998
> [998] Fix label of PortUsage

- backend/application/syson-sysml-validation/pom.xml
- integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
- integration-tests/cypress/workbench/Explorer.ts
- scripts/update-sirius-web.js
> [releng] Fix Sirius Web version in syson-sysml-validation

- CHANGELOG.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
- frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Bug: https://github.com/eclipse-syson/syson/issues/1012
> [1012] Allow package nodes to be smaller than their default size

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1006
> [1006] Display isInitial and isDefault of FeatureValue Core tab

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVRelationshipTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1020
> [1020] Remove multiplicity data from edge label

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SysmlFactoryImpl.java
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1009
> [1009] Allow SysMLFactory to create null unsettable Enum

- CHANGELOG.adoc
- backend/application/syson-application/Dockerfile
- doc/content/modules/developer-guide/pages/index.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
- integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/1023
> [1023] Update SysIDE dependency to 0.8.0

- CHANGELOG.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
- frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNodeLayoutHandler.ts
- frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Bug: https://github.com/eclipse-syson/syson/issues/1012
> [1012] Allow import package nodes to be smaller than their default size

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/SuccessionAsUsageTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1028
> [1028] Improve SuccessionAsUsage with implicit source

- frontend/syson/src/extensions/SysONFooter.tsx
- frontend/syson/vite.config.js
Instead of changing the `SysONFooter.tsx` on every new version, (and artificially increase the versions of this file), this PR proposes to compute the displayed application version directly from the package.json
from end user perspective nothing has changed
> [enh] Footer displays app version from value extracted from package.json

- backend/application/syson-application/src/test/resources/scripts/dump-test-data.sh
> [cleanup] Add column names to syson-test-database.sql test data

- CHANGELOG.adoc
- backend/services/syson-services/src/main/java/org/eclipse/syson/util/ViewConstants.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractDefinitionNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractUsageNodeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1024
> [1024] Add wrap option on definition and usage node label

- .github/workflows/build.yml
We only want to execute cypress tests on PR branches
> [releng] Do not launch cypress tests on main branch

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [1042] Improve SuccessionAsUsage defining new the actions

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [1045] Improve export to properly handle named SuccessionAsUsage

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1080
> [1080] Improve import and resolution of ConjugatedPort

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/VariantMembershipImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/VariantMembershipImplTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/870
> [870] Fix an issue while computing the name of VariantMembership

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-application/src/test/resources/part_changes.json
- backend/application/syson-application/src/test/resources/simple_project.json
- backend/application/syson-application/src/test/resources/simple_project_changes.json
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TransitionUsageImpl.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
action
Bug: https://github.com/eclipse-syson/syson/issues/1048
> [1048] Improve TransitionUsage to improve control of succession of

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ContainmentReferenceHandler.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ParameterMembershipImpl.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [1094] Improve the import of guard on TransitionUsages

- CHANGELOG.adoc
- backend/application/syson-application/src/test/resources/part_changes.json
- backend/application/syson-application/src/test/resources/simple_project.json
- backend/application/syson-application/src/test/resources/simple_project_changes.json
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorAsUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ItemUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PartUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectionDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectionUsageImplTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1105
> [1105] Implement ConnectionDefinition derived references and operations

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1037
> [1037] "Add existing nested element" tool on the Action Flow compartment

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/ImplicitSpecializationsTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ActionDefinitionImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ActionUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/BehaviorImpl.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
- scripts/check-coverage.jsh
Bug: https://github.com/eclipse-syson/syson/issues/1122
> [1122] Add support for Behavior/Step parameters implicit redefinition

- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorImpl.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectorImplTest.java
Bug: https://github.com/eclipse-syson/syson/issues/1079
> [1079] Fix an Stackoverflow in the Connector implementation

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/checker/SysmlImportExportChecker.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/sysml/impl/ActionDefinitionImplTest.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SpecializationImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/VirtualLinkAdapter.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1029
- [] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.
> [1029] Fix name resolution on element reference by implicit elements

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1143
> [1143] Implement export of Decision Transition Usages

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/SysMLv2SemanticImportChecker.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1148
> [1148] Fix computation of Succession source and target implicit features

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1158
> [1158] Fix imported TransitionFeatureKind value on accept and do

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/SySONLibraryPublicationHandler.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/publication/SySONLibraryPublicationTests.java
- backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/dump-test-data.sh
- backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/initialize-test-data.sh
- backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/syson-test-database.sql
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1155
> [1155] Remove the imported EAnnotation from published libraries

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1164
> [1164] Fix imported RequirementConstraintKind on assume and require

- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
- integration-tests/cypress/e2e/project/details/details.cy.ts
- integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
- integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
- integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
- integration-tests/cypress/pages/Project.ts
- integration-tests/cypress/support/server/deleteProjectCommand.ts
- integration-tests/cypress/support/serverCommands.js
- integration-tests/cypress/support/testIdCommands.ts
- integration-tests/cypress/workbench/Explorer.ts
> [test] Enable skipped tests

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1160
> [1160] Use TextArea for body properties

- backend/application/syson-application/src/test/java/org/eclipse/syson/OnNoDefaultLibrariesTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/SysONNoDefaultLibrariesTestConfiguration.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/SysONNoLoadDefaultLibrariesOnApplicationStartTestConfiguration.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/SysONTestsProperties.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/objects/ObjectCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/relatedelements/view/RelatedElementsViewTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewSubsettingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAnnotatingElementTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVBorderNodePortCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVRelationshipTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeExtensionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewBindingConnectorAsUsageFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewFlowConnectionFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVFlowConnectionFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/rest/RestControllerIntegrationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
- scripts/check-coverage.jsh
> [test] Add possibility to launch tests without default libraries

- doc/content/modules/user-manual/pages/features/library-import.adoc
- doc/content/modules/user-manual/pages/features/publication.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
- scripts/check-coverage.jsh
> [doc] Update doc

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/textual/SysMLElementSerializerTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [1173] Fix the export of LiteralString not wrapped in double quotes

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVActionFlowTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
- scripts/check-coverage.jsh
Bug: https://github.com/eclipse-syson/syson/issues/1176
> [1176] Fix creation of TransitionUsage to "Done" ActionUsage

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1162
> [1162] Implement TextualRepresentation textual export

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
- backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ElementTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [1183] Fix Element#isLibraryElement for elements inside LibraryPackage

- .github/workflows/generate-maven-sbom.yml
- .github/workflows/generate-npm-sbom.yml
> [releng] Update sbom workflows

- CHANGELOG.adoc
> [doc] Remove work in progress note in changelog

- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
> [doc] Remove work in progress note in release notes

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewExhibitStateWithReferencedStateFromPartsTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewWithTopNodesTestProjectData.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ExhibitStateWithReferenceNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1196
> [1196] Add New Exhibit State with referenced State tool in part usage

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1214
Bug: https://github.com/eclipse-syson/syson/issues/1216
Bug: https://github.com/eclipse-syson/syson/issues/1217
> Implement textual export of ForkNode, JoinNode and MergeNode

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1249
> [1249] Implement textual import/export of AcceptActionUsage

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetIntermediateContainerCreationSwitch.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/GetChildCreationSwitchTest.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/ElementInitializerSwitchTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1247
> [1247] Type new ViewUsage from Explorer view with GeneralView ViewDef

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1252
- [] Have you included an update of the [documentation](https://doc.mbse-syson.org) in your pull request? Please ask yourself if an update (installation manual, user manual, developer manual...) is needed and add one accordingly.
> [1252] Implement textual export of TriggerInvocationExpression

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateSubactionNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/ActionsCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1233
> [1233] Add new tools to create State sub actions in general view

- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/details/view/DetailsViewControllerIntegrationTests.java
> [test] Add an integration test for the Details view

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PerformActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ReferencingPerformActionNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateSubactionNodeToolProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug:https://github.com/eclipse-syson/syson/issues/1267
> [1267] Improve the New Perform tool selection dialog

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/checkers/CheckNodeInCompartment.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ReferencingPerformActionNodeToolProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug:https://github.com/eclipse-syson/syson/issues/1269
> [1269] New perform action with reference is now automatically revealed

- .github/workflows/generate-maven-sbom.yml
- .github/workflows/generate-npm-sbom.yml
> [releng] Update sbom github actions

- CHANGELOG.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
- frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Bug: https://github.com/eclipse-syson/syson/issues/1297
> [1297] Fix Package graphical node children layout

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/omnibox/PredicateCanEditingContextPublishSysMLProject.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/omnibox/OmniboxControllerIntegrationTests.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
This PR is a draft until Sirius Web 2025.4.2 is released and consumed by SysON (it relies on a method in `ISemanticDataSearchService` that has been introduced after 2025.4.1).
Fixes #1281
> [1281] Prevent editing context loading when querying omnibox commands

- CHANGELOG.adoc
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StateTransitionCompartmentNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/StatesCompartmentNodeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1300
> [1300] Fix wrong tool section name found in some compartments' palette

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GVDescriptionNameGenerator.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1303
> [1303] Fix Constraint creation tools name inside Requirement

- backend/application/syson-application/src/test/java/org/eclipse/syson/AbstractIntegrationTests.java
- backend/application/syson-application/src/test/resources/spring.properties
> [test] Improve the Spring test context caching to speed up tests

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/ViewUsage.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SysmlPackageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ViewUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/resources/model/sysml.ecore
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1310
> [1310] Remove derived flag for ViewUsage#exposedElement feature

- CHANGELOG.adoc
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorAsUsageImpl.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
- integration-tests/cypress/e2e/project/details/details.cy.ts
Bug: https://github.com/eclipse-syson/syson/issues/1324
> [1324] Fix an issue that prevents ending up with a reference null

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVViewUsageExposedElements.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/ViewUsageExposedElementsTestProjectData.java
- backend/application/syson-application/src/test/resources/scripts/database-content/ViewUsage-ExposedElements.sql
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AnnotatingElementOnRelationshipNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ExhibitStateWithReferenceNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/NamespaceImportNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PartUsageFeatureTypingNodeToolProvider.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PartUsageSubsettingNodeToolProvider.java
- backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/ViewUsageNodeDescriptionProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
> [1314] Update ViewUsage#exposedElement when manipulating GeneralView

- scripts/check-coverage.jsh
> [releng] Update coverage thresholds

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysONReadOnlyObjectPredicateDelegate.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
This should fix #1339 by making the Details view extensible in how it computes whether an element is read-only or not.
> [1339] Make Details view more extensible to determine read-only-ness

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1359
> [1359] Handle textual export of ViewUsage

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
- backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/DeleteService.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/RelatedElementsSwitch.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/DeleteServiceTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
> [fix] Delete associated MembershipExpose when deleting an Element

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/objects/ObjectCreationTests.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/CreateRepresentationInputProcessor.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/SysONExplorerTreeItemContextMenuEntryProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
> [fix] Create a General View diagram when a ViewUsage is created

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2LabelService.java
- backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/MembershipExposeItemProvider.java
- backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/NamespaceExposeItemProvider.java
> [fix] Improve Expose labels in Explorer view

- doc/content/modules/user-manual/partials/nav-tuto.adoc
- doc/content/modules/user-manual/partials/nav-ui.adoc
> [doc] Reference Flashlight tutorials in TOC

- CHANGELOG.adoc
- backend/application/syson-sysml-import/src/main/resources/syside-cli.js
- doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1385
> [1385] Update SysIDE dependency to 0.9.0

- .github/workflows/build.yml
- .github/workflows/doc-gen.yml
- .github/workflows/generate-maven-sbom.yml
- .github/workflows/generate-npm-sbom.yml
- .github/workflows/pull-request.yml
> [releng] Update all workflow actions

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1411
> [1411] Add standard libraries migration participants

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
> [fix] Fix value property in Details view

- doc/content/antora.yml
- docker-compose.yml
> [fix] Fix antora and docker-compose release version

- backend/application/syson-application/src/test/resources/scripts/dump-test-data.sh
- backend/application/syson-application/src/test/resources/scripts/initialize-test-data.sh
> [test] Fix integration test data scripts

- frontend/syson/src/ReactFlow.css
- frontend/syson/src/index.tsx
> [fix] Add missing ReactFlow.css

- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewAddExistingElementsTestProjectData.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
> [fix] Do not expose elements twice

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/testers/ExpandAllTreeItemTester.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/testers/TreePathTester.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerFilterService.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerTreePathProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1458
> [1458] Fix Explorer context menu that was loaded twice on a menu item

- CHANGELOG.adoc
- doc/content/modules/installation-guide/pages/migration-process.adoc
> [doc] Update migration process

- CHANGELOG.adoc
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ContainmentReferenceHandler.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/NonContainmentReferenceHandler.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ReferenceNodeTester.java
- backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/SysIDENonContainmentIncompatibilitiesHandler.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MetadataAccessExpressionImpl.java
- doc/content/modules/user-manual/pages/release-notes/2025.10.0.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1454
> [1454] Fail to import model with MetadataAccessExpression

- CHANGELOG.adoc
- backend/application/syson-application/src/test/resources/package1.json
- backend/application/syson-application/src/test/resources/part_changes.json
- backend/application/syson-application/src/test/resources/part_relationships.json
- backend/application/syson-application/src/test/resources/simple_project.json
- backend/application/syson-application/src/test/resources/simple_project_changes.json
- backend/application/syson-application/src/test/resources/simple_project_roots.json
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/VirtualLinkAdapter.java
- backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2JsonSerializer.java
- doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
- scripts/check-coverage.jsh
Bug: https://github.com/eclipse-syson/syson/issues/1467
> [1467] Fix issue in JSON serialization - @id and elementId are now same

- doc/content/modules/user-manual/pages/faq/faq.adoc
> [doc] Fix broken link

- doc/content/modules/developer-guide/examples/new_objects_from_text.py
- doc/content/modules/developer-guide/pages/api/api-cookbook.adoc
- doc/content/modules/developer-guide/pages/api/api.adoc
- doc/content/modules/developer-guide/partials/element_owned_elements_recipe.adoc
- doc/content/modules/developer-guide/partials/new_objects_from_text.adoc
> [doc] Add new recipe to cookbook about new objects from text GraphQL API

- CHANGELOG.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
> [doc] Update release notes and changelog

- CHANGELOG.adoc
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysONDefaultLibrariesConfiguration.java
- backend/application/syson-application/pom.xml
- backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
- backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/LibraryNamespaceProviderTests.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationAccumulator.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/MetadataUsageImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ILibraryNamespaceProvider.java
- backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/LibraryNamespaceProvider.java
- doc/content/modules/user-manual/pages/release-notes/2025.10.0.adoc
> Add implicit Subclassification (Subsetting) when using semantic MetadataUsage #1432

- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoader.java
- backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysONDefaultResourceProvider.java
- backend/services/syson-services/src/main/java/org/eclipse/syson/services/ColorProvider.java
- backend/services/syson-services/src/test/java/org/eclipse/syson/services/AbstractServiceTest.java
- backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/IViewDescriptionProvider.java
- backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/SysONExplorerTreeDescriptionProvider.java
> [fix] Use new isReadOnlyParameter on ResourceMetadataAdapter

- doc/content/modules/user-manual/pages/features/cm.adoc
> [doc] Add missing line break

- doc/content/modules/user-manual/pages/hands-on/tutorials/flashlight.adoc
Bug: https://github.com/eclipse-syson/syson/issues/1551
> [doc] Update Flashlight tutorial in documentation

- doc/content/modules/user-manual/pages/features/general-view.adoc
- doc/content/modules/user-manual/pages/release-notes/2025.10.0.adoc
> [doc] Fix typos
