CHANGELOG.adoc
backend/application/syson-application-configuration/pom.xml

Bug: https://github.com/eclipse-syson/syson/issues/71

[71] Add commons-io library in syson-application-configuration

---

CHANGELOG.adoc
frontend/syson-components/src/nodes/package/SysMLPackageNode.tsx
frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts

This PR fixes the following issues:
- Increase the `maxWidth` of the Package headers to handle longer labels, especially when the Package has its default size
- Replaced the manual computation of the header width with `width: fit-content` (the previous version used `ch` to compute the width, which is not appropriate)
- Fix a layout issue for Package children that could overlap the Package's west border after a move
**Note**: this PR doesn't add ellipsis to Package labels that are too long for the Package header. This will be fixed in Sirius Web Label and can be reused for Package once it is available.

[86] Improve Package headers' width and children layout

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/util/DescriptionNameGenerator.java
backend/services/syson-services/src/test/java/org/eclipse/syson/util/DescriptionNameGeneratorTest.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/EmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/PackageNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewEdgeToolSwitch.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootPartUsageNodeDescriptionProvider.java

This PR adds a 2 new public methods in `DescriptionNameGenerator` to get the name of a creation tool. These methods add spaces before capital letters of type names, and removes "Usage" from type names.  
> [!NOTE]
> Let me know if `DescriptionNameGenerator` is not the right place to put these methods. It made sense to me to put them next to the methods that compute the name of Node/Edge Description, but it may not fit the architecture you have in mind.
This PR also updates all the node/edge creation tools to use this new API.
Note that I  am not sure about the updated Edge creation tool for `BindingConnectorAsUsage`, which is now named "Binding Connector As". It doesn't look right to me, so let me know if I should make an exception for this specific edge and keep the "Usage".

[88] Add spaces and remove "Usage" in node/edge creation tool names

---

backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/ToolSectionDescription.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/EmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/PackageNodeDescriptionProvider.java

Using Java.lang.Map to describe tool sections does not guarantee the order of its entries.
Since we want to control the palette sections' order we need to change how the tool sections are expressed.
Bug: https://github.com/eclipse-syson/syson/issues/93

[93] Tool sections should appear always in the same order

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysONReferenceWidgetRootCandidateSearchProvider.java
backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/ElementItemProvider.java

Bug: https://github.com/eclipse-syson/syson/issues/105

[105] Show standard libraries in Reference Widget's model browser dialog

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubclassificationEdgeDescriptionProvider.java

Bug: https://github.com/eclipse-syson/syson/issues/118

[118] Subclassification edge is no longer visible

---

CHANGELOG.adoc
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/RequirementDefinitionImpl.java
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/RequirementUsageImpl.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/RequirementDefinitionSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/RequirementSubjectCompartmentNodeToolProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GVDescriptionNameGenerator.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/RVDescriptionNameGenerator.java
backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/RequirementViewDiagramDescriptionProvider.java
backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/nodes/FakeNodeDescriptionProvider.java
backend/views/syson-diagram-requirement-view/src/main/java/org/eclipse/syson/diagram/requirement/view/services/RequirementViewNodeToolSectionSwitch.java

This commit adds an "attributes" compartment in RequirementUsage, and uniformized the compartments of RequirementDefinition with RequirementUsage.
Bug: https://github.com/eclipse-syson/syson/issues/147

[147] Refactor Requirement compartments

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractDefinitionNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractUsageNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/UsageNestedUsageEdgeDescriptionProvider.java

Add "Become nested ":
- Attribute for all usages,
- Item for all usage,
- Part for all usage and PartDefinition
- Port for all usages
Bug: https://github.com/eclipse-syson/syson/issues/151

[151] Add some missing "Become nested XXX" edge tools.

---

CHANGELOG.adoc
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/DefinitionNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UsageNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java

This PR covers the node tools for the following usages:
| is Col can be created in Row? | Attribute | Item | Part | Port |
|------------------------------|:---------:|:----:|:----:|:----:|
| Attribute                    |     c     |   x  |   x  |   x  |
| Item                         |     c     |   ✓  |   ✓  |   ✓  |
| Part                         |     c     |   ✓  |   ✓  |   c  |
| Interface                    |     c     |   ✓  |   ✓  |   c  |
| Port                         |     c     |   x  |   x  |   c  |
| Action                       |     ✓     |   c  |   ✓  |   ✓  |
| Constraint                   |     ✓     |   ✓  |   ✓  |   ✓  |
| Requirement                  |     c     |   ✓  |   ✓  |   ✓  |
where c means that this is covered by a compartment node tool, and x means this is …

[154] Add missing node tools in existing usage elements

---

backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java

and Item Definition should have the node tool "New Item" in its palette
Bug: https://github.com/eclipse-syson/syson/issues/151

[151] Item usage should have the become nested edge tool to part def

---

CHANGELOG.adoc
backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/SysmlToAst.java

Bug: https://github.com/eclipse-syson/syson/issues/160
Signed-off-by: Guillaume Escande <guillaume.escande@obeosoft.fr>

[160] Add explicit usage of node to call syside javascript file

---

CHANGELOG.adoc
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/UsageNestedUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java

Missing cases:
- Nested Actions of Actions
- Nested Constraints of Constraints
- Nested Constraints of Requirements
Bug:  https://github.com/eclipse-syson/syson/issues/163

[163] Add missing composite edges between usage and compartment content

---

backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolSwitch.java

At the moment, the edge tool preconditions are evaluated as soon as the node that contains the edge tool is selected. Since no edges are built at this stage, edge variables are not instantiated and accessing these variables raises errors.
A proposal (https://github.com/eclipse-sirius/sirius-web/issues/2930) is made to evaluate preconditions when the edge target is selected. That way, the edge variables will be set and could be used in services.
The fix consists to remove the precondition in the edge tool to avoid errors.
Bug: https://github.com/eclipse-syson/syson/issues/169

[fix] Edge tool preconditions are not properly supported

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2LabelService.java

Bug: https://github.com/eclipse-syson/syson/issues/199

[199] Fix rename element action in Explorer view

---

CHANGELOG.adoc
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/PortUsageBorderNodeDescriptionProvider.java

Bug: https://github.com/eclipse-syson/syson/issues/204

[204] Change label position to outside for ports in InterconnectionView

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDefinitionOwnedUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewToolService.java

The `ViewToolService` doesn't attempt to change the container of a part if it would create a circular containment reference. This includes "Become Nested Part" tool as well as nested part edge reconnection tools.
An error message is logged in the console and in the workbench via the `IFeedbackMessageService`.
Bug: https://github.com/eclipse-syson/syson/issues/229

[229] Prevent circular containment of nested parts

---

CHANGELOG.adoc
backend/tests/syson-tests/src/main/java/org/eclipse/syson/tests/architecture/AbstractCodingRulesTests.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java

`EcoreUtil.delete` looks for all the crossReferences of the element to delete. This takes a lot of time when all the Sysml standard libraries are loaded in the resource set. We can replace `EcoreUtil.delete` with `DeleteService.deleteFromModel`, which is way faster. This shouldn't be an issue because `DeleteService.deleteFromModel` is already used in various places in the code to delete elements.
This PR also adds a check in the `AbstractCodingRulesTests` class, although it is not used at the moment, it will be useful to check that no class uses `EcoreUtil.delete` once we enforce the coding rules.
Bug: https://github.com/eclipse-syson/syson/issues/305

[305] Fix performance issue when using EcoreUtil.delete

---

backend/services/syson-services/src/main/java/org/eclipse/syson/services/RelatedElementsSwitch.java

Start and Done special actions break the automatic cleanup of succession edge when they are deleted from the diagram.
Bug: https://github.com/eclipse-syson/syson/issues/269

[fix] Start and Done prevent succession removal when removed

---

CHANGELOG.adoc
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/StateDefinitionImpl.java
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/StateSubactionMembershipImpl.java
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/StateUsageImpl.java
backend/services/syson-services/src/main/java/org/eclipse/syson/util/DescriptionNameGenerator.java
backend/services/syson-services/src/main/java/org/eclipse/syson/util/IDescriptionNameGenerator.java
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/SuccessionEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDefinitionOwnedUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/MergedReferencesCompartmentItemNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/SuccessionEdgeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/STVDescriptionNameGenerator.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/DefinitionNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/FakeNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/UsageNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewNodeToolSectionSwitch.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewToolService.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/tools/StateTransitionActionToolProvider.java

- M2 implementation of get[Entry|Do|Exit]Action on
StateUsage and StateDefinition
- M2 implementation of getAction on StateSubactionMembership
- New CompartmentItem NodeDescription to handle multiple EReferences
instead of only one EReference
- Update State Transition list items to use the entry/do/exit actions
references from StateUsage and StateDefinition.
- Add action creation tools on StateUsage and StateDefinition.
- Add necessary services for actions creation. Refactor existing code.
Remains to be done in this task:
- Drag'n'Drop of actions
- Limit creation of actions to one of each entry/do/exit per state
- Add action creation tools to actions container
Bug: https://github.com/eclipse-syson/syson/issues/333

[333] State entry/do/exit actions items in dedicated container

---

CHANGELOG.adoc
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/AllocateEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeService.java

+ fix a typo in the edge target reconnection service name
Bug: https://github.com/eclipse-syson/syson/issues/356

[356] The Allocate edge is not displayed in the Action Flow View diagram

---

backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/MergedReferencesCompartmentItemNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewToolService.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/tools/StateTransitionActionToolProvider.java

- Make Kind property from StateSubactionMembership visible from Action
- Make kind property from StateSubactionMembership visible on Core properties
- Prefix the label of the entry/do/exit actions with entry/do/exit
- Add Entry/Do/Exit action creation tools on StateUsage and StateDefinition. Tools only allow the creation of one of each kind of actions.
- Deactivated the tools on the "actions" container as it requires additional modifications.
- Improved the "Add existing elements" tool for diagram initialisation. Limited as sub states are not handled in the recursive call.
Bug: https://github.com/eclipse-syson/syson/issues/333

[333] State subaction tools and properties

---

backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/CompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/DefinitionNodeDescriptionProvider.java

- Add entry/do/exit action creation tools on "actions" container.
- Set droppable nodes for StateDefinition.
Bug: https://github.com/eclipse-syson/syson/issues/333

[333] Add "actions" container creation tools

---

backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/Appender.java
backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java

This commit:
* Fixe an IndexOutOfBound while resolving name
* Remove the generic caseUsage and caseDefinition that all most of defintion and Usage. Instead it declares all case in a separate method. We need to do that because some usage or definition are not handle has "children" but has shorthand notation.

Fix Export problems and reduce perimeter

---

backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/DeresolvingNamespaceProvider.java

[196] Extract deresolving name logic so it can be used during import

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/RelatedElementsSwitch.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewNodeToolSectionSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ExhibitStatesCompartmentItemNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/AbstractViewNodeToolSectionSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateTransitionActionCompartmentToolProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateTransitionToggleExhibitStateToolProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GVDescriptionNameGenerator.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/ActionsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildPartUsageNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FirstLevelChildPartUsageNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootDefinitionNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/RootUsageNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/STVDescriptionNameGenerator.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/DefinitionNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/FakeNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionActionsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/UsageNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewNodeToolSectionSwitch.java

- Add contextual palette tools to "Exhibit" or "Set as not exhibited" a state
- Add properties view checkbox "is Exhibited" to exhibit or unexhibit a state
- Modify the way to directly create an exhibit state, now creates a State and and ExhibitState and adds the relation instead of relying on an ExhibitState without setting "exhibitedState".
- Refactor services
- GeneralView diagram still requires adjustments on the display of states and exhibit
Bug: https://github.com/eclipse-syson/syson/issues/393

[393] Exhibit States tools on STV

---

backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/AssertConstraintUsageWithOperatorExpressionTestModel.java
backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/IsImplicitTest.java
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ActorMembershipImpl.java

Partial implementation of ReturnParameterMembership, implementation of NullExpression and an API to exclude implicit elements

[196] Implementation of AssertConstraintUsage in export to textual files

---

doc/content/modules/installation-guide/pages/troubleshooting.adoc
doc/content/modules/user-manual/pages/features/action-flow-view.adoc
doc/content/modules/user-manual/pages/features/details.adoc
doc/content/modules/user-manual/pages/features/editor.adoc
doc/content/modules/user-manual/pages/features/explorer.adoc
doc/content/modules/user-manual/pages/features/general-view.adoc
doc/content/modules/user-manual/pages/features/homepage.adoc
doc/content/modules/user-manual/pages/features/interconnection-view.adoc
doc/content/modules/user-manual/pages/features/keyboard-shortcuts.adoc
doc/content/modules/user-manual/pages/features/related-elements.adoc
doc/content/modules/user-manual/pages/features/representations-view.adoc
doc/content/modules/user-manual/pages/features/state-transition-view.adoc
doc/content/modules/user-manual/pages/features/validation.adoc
doc/content/modules/user-manual/pages/hands-on/how-tos/explorer.adoc
doc/content/modules/user-manual/pages/hands-on/how-tos/model-management.adoc
doc/content/modules/user-manual/pages/hands-on/how-tos/project-management.adoc
doc/content/modules/user-manual/partials/before-you-start-experimental-all.adoc

Contribute a new partial "before you start" which specify features status and usage which is used by all the sections describing a feature. 
Fix a reference in the troubleshooting page.

[doc] Fix errors in documentation

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/DoneActionNodeToolProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StartActionNodeToolProvider.java

Bug: https://github.com/eclipse-syson/syson/issues/468

[468] Rename creation tools for Start and Done actions

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java

bug: https://github.com/eclipse-syson/syson/issues/470

[470] Reduce the default height of the Package node in diagrams

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractControlNodeActionNodeDescriptionProvider.java

Bug: https://github.com/eclipse-syson/syson/issues/477

[477] Add Direct Edit tool in control nodes palette

---

CHANGELOG.adoc
backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstObjectParser.java
backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java

When documentation is imported from a textual sysml file, the useful text is framed by /*  */, which, according to the sysml specification, should not be part of the documentation itself.
This should be fixed in the import module, by only adding the content of the textual documentation.

[459] Correct Documentation import

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java

Bug: https://github.com/eclipse-syson/syson/issues/494

[494] Change the default name of the transition element

---

CHANGELOG.adoc
backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/NamespaceItemProvider.java
backend/metamodel/syson-sysml-metamodel-edit/src/main/resources/icons/full/ovr16/VisibilityKind_private.svg
backend/metamodel/syson-sysml-metamodel-edit/src/main/resources/icons/full/ovr16/VisibilityKind_protected.svg

This commits add two overlay decorators for both private and protected visibility, and includes the supporting code so that any SysMLv2 element which has such visibility will have an overlayed decorator.
We decided to not add the "public" decorator considering that currently everything is created "public" by default and that would clutter and add noise on the UI.

Add visibility decorators

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeCreationTests.java

Bug: https://github.com/eclipse-syson/syson/issues/542

[542] Enable Action's sub-node creation tests for free form items

---

CHANGELOG.adoc
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java

The InterfaceUsage created by the New interface edge tool in the Interconnection View diagram are now created under closest containing Definition/Package.
Bug: https://github.com/eclipse-syson/syson/issues/261

[261] Change InterfaceUsage container in Interconnection View

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ItemUsageBorderNodeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeService.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeToolSectionSwitch.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/606

[606] Prevent nested part to be rendered as border nodes

---

doc/content/modules/installation-guide/pages/how-tos/install.adoc
doc/content/modules/user-manual/pages/faq/faq.adoc
doc/content/modules/user-manual/pages/features/keyboard-shortcuts.adoc

Update documentation sections:
* FAQ: to better explain that the API does not yet exist but it is our intent.
* Keyboard Shortcuts: to add the selection without palette and selection without move in a diagram.
* Install: to move the information about using the .0 version to the beginning of the section.

[doc] Update FAQ, keyboard shortcut and install sections

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/619

[619] Fix Inherited members inside compartments don't display palette

---

CHANGELOG.adoc
backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/MembershipComputer.java
backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/PartUsageImplTest.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/651

[651] Remove owning Usage memberships from inherited memberships

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/JavaServiceIsCalledChecker.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractCompartmentNodeToolProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ActorCompartmentNodeToolProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ObjectiveRequirementCompartmentNodeToolProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/ObjectiveRequirementWithBaseRequirementCompartmentNodeToolProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementDefinitionActorsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementDefinitionSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageActorsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionActorsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionObjectiveRequirementCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseDefinitionSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageActorsCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageObjectiveRequirementCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/UseCaseUsageSubjectCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc

This PR also contains the following refactorings:
- Update `AbstractCompartmentNodeToolProvider` to support selection dialog
- Remove selection dialog related code in existing subclasses of `AbstractCompartmentNodeToolProvider`
- Extract common methods from `DiagramDirectEditListener` in `UtilService` to make them reusable in other services (`setFeatureTyping`, `setSubsetting`, etc)
- Uniformize the use of `ElementInitializerSwitch` in tools using selection dialog
Bug: https://github.com/eclipse-syson/syson/issues/660
To merge after #659

[660] Allow to select existing Requirements in objective tool

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts

Bug: https://github.com/eclipse-syson/syson/issues/674
To rebase/merge after #672

[674] Ensure that dropped nodes are always collapsed

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/687

[687] Fix action drop from the diagram to an action flow compartment.

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
doc/content/modules/user-manual/pages/release-notes/2024.9.0.adoc
integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
integration-tests/cypress/workbench/Diagram.ts

Bug: https://github.com/eclipse-syson/syson/issues/709

[709] Allow to drop Definition from the explorer on an Usage to type it

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetIntermediateContainerCreationSwitch.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

User can now create a new Comment element from the explorer view.
Bug: https://github.com/eclipse-syson/syson/issues/731
Signed-off-by: Jessy Mallet <jessy.mallet@obeo.fr>
Be careful, before merging this PR, PR https://github.com/eclipse-syson/syson/pull/728 should be merged.

[731] Allow Comment creation from Explorer

---

doc/docs-site/antora-playbook.yml

Change default start page to have the latest tag version as default page of documentation.

[doc] Change default start page to have the latest tag version

---

CHANGELOG.adoc
backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/740

[740] Fix missing declaredName after exporting an annotating element

---

CHANGELOG.adoc
backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstContainmentReferenceParser.java
backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertAllocationTest/allocation.ast.json
backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertAllocationTest/allocation.sysml
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/744
This PR **doesn't** allow to import the `AllocationTest.sysml` file in SysML-v2-Release _Simple Tests_. This file emphasize other issues related to namespace resolution that are out of the scope of this PR.

[744] Fix containment of imported Allocation and AllocationDefinition

---

CHANGELOG.adoc
backend/application/syson-application-configuration/pom.xml
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/761

[761] Make Declared Short Name accessible from the Core tab

---

CHANGELOG.adoc
backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
backend/views/syson-diagram-common-view/src/test/java/org/eclipse/syson/diagram/common/view/services/ViewLabelServiceTest.java
backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/BindingConnectorAsUsageEdgeDescriptionProvider.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewLabelService.java
backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionTests.java
backend/views/syson-diagram-statetransition-view/src/test/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionTests.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/765
Rational for the changes in the PR:
- The name of transition is never visible (8.2.3.17). The transition label contains only the trigger expression and the action usage
- The name of a succession is visible (8.2.3.9) via the rule _UsageDeclaration_
- The name of a dependency is visible (8.2.3.3) via the rule _Identification_
- The name of a flow is visible (8.2.3.13) via the rule _UsageDeclaration_
- The name of a message is visible (8.2.3.13) via the rule _UsageDeclaration_
- The name of an interface is visible (8.2.3.14) via the rule _UsageDeclaration_
- The name of a binding connection is always "=" (8.2.3.13)
- The name of an allocation is always `<<allocate>>` (8.2.3.15)
The rule _Identification_ is a wrapper for short name + …

[765] Remove default name of relationships and improve edge labels

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/GetChildCreationSwitchTest.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/767

[767] Allow to create dependencies in the explorer

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/checkers/CheckNodeOnDiagram.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeExtensionCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DropFromExplorerTester.java
backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/ImplicitSpecializationsTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/services/SemanticRunnableFactory.java
backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/ActionFlowViewEmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewEmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionTests.java
backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionViewEmptyDiagramNodeDescriptionProvider.java
backend/views/syson-diagram-statetransition-view/src/test/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionTests.java
backend/views/syson-diagram-tests/pom.xml
backend/views/syson-diagram-tests/src/main/java/org/eclipse/syson/diagram/tests/checkers/DiagramDescriptionHasNoEmptyDiagramNodeChecker.java
backend/views/syson-diagram-tests/src/main/java/org/eclipse/syson/diagram/tests/checkers/DiagramDescriptionHasOneEmptyDiagramNodeChecker.java
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/771

[771] Allow the drop of elements on empty diagram nodes

---

CHANGELOG.adoc
backend/application/syson-application-configuration/.checkstyle
backend/application/syson-application/.checkstyle
backend/application/syson-sysml-export/.checkstyle
backend/application/syson-sysml-import/.checkstyle
backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/.checkstyle
backend/metamodel/syson-siriusweb-customnodes-metamodel/.checkstyle
backend/metamodel/syson-sysml-metamodel-edit/.checkstyle
backend/metamodel/syson-sysml-metamodel/.checkstyle
backend/services/syson-services/.checkstyle
backend/tests/syson-tests/.checkstyle
backend/views/syson-diagram-actionflow-view/.checkstyle
backend/views/syson-diagram-common-view/.checkstyle
backend/views/syson-diagram-general-view/.checkstyle
backend/views/syson-diagram-interconnection-view/.checkstyle
backend/views/syson-diagram-statetransition-view/.checkstyle
backend/views/syson-diagram-tests/.checkstyle
doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/775

[775] Exclude src/test/resources from checkstyle

---

CHANGELOG.adoc
doc/content/modules/user-manual/pages/release-notes/2025.1.0.adoc
frontend/syson/src/extensions/SysONDocumentTreeItemContextMenuContribution.tsx
frontend/syson/src/extensions/SysONExtensionRegistryMergeStrategy.ts
frontend/syson/src/extensions/SysONObjectTreeItemContextMenuContribution.tsx
frontend/syson/src/index.tsx
integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
integration-tests/cypress/e2e/project/explorer/semanticElementCreationTests.cy.ts
integration-tests/cypress/usecases/SysMLv2.ts
integration-tests/cypress/workbench/Explorer.ts

Bug: https://github.com/eclipse-syson/syson/issues/889

[889] Remove New object/representation contextual menu entry for libraries

---

.github/workflows/generate-maven-sbom.yml
.github/workflows/generate-npm-sbom.yml

As previously discussed, this PR aims to bootstrap the EF Security Team initiative of implementing automated SBOM generation for projects and uploading them to our DependencyTrack instance, with the goal of enhancing software supply chain security.
We wanted this to seamlessly integrate with your existing release processes, so we designed and implemented 2 generation workflows:
- 1 maven workflow: meant to generate an SBOM for the backend product (i.e. syson/backend/application/)
- 1 npm workflow: meant to generate an SBOM for the frontend product (i.e syson/frontend/)
Currently the workflows are triggered by either pushes to the main branch that modify dependency files or by pushing new tags. Several Cyclonedx ecosystem specific plugins are used to generate the SBOMs, which are then …

Add SBOM generation and upload to DependencyTrack workflows

---

frontend/syson/src/extensions/SysONExtensionRegistryMergeStrategy.ts
frontend/syson/src/index.tsx

Temporary hack to remove the Libraries menu
To remove when the libraries mechanism will be fully implemented in Sirius Web

[releng] Remove Libraries Menu

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/1091

[1091] Fix qualified names in FeatureReferenceExpression export

---

CHANGELOG.adoc
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
backend/views/syson-tree-explorer-view/src/test/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServicesTest.java
doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
scripts/check-coverage.jsh

Fix behavior of hasChildren management of syson explorer when handling model elements from non-sysml domains. 
It now falls back to SiriusWeb implementation when necessary.

[1077] Fix explorer in case of non-sysml domain

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/1172

[1172] Uniformize the import of LiteralString value

---

CHANGELOG.adoc
backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc

This PR makes LibraryPackage's `isStandard` checkbox read-only in the details view. The issue originally proposes to remove the checkbox, but I think it provide relevant information to the end user. 
Making it read-only let the user get the information while enforcing the fact that SysON does not support non-SysML, non-KerML standard libraries.
Note that the PR does not address the question of the textual import of a standard library package.
Fixes #1244

[1244] Make LibraryPackage's isStandard checkbox read-only

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
backend/application/syson-sysml-import/pom.xml
backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc

SysIDE does a bad job at parsing multiplicity ranges with upper and lower bounds: it produces a `MultiplicityRange` with an  `OperatorExpression` containing features ultimately containing `LiteralIntegers`, while the specification (and the pilot implementation) indicate to create a `MultiplicityRange` containing directly the `LiteralIntegers`.
Similarly, SysIDE creates `FeatureChainExpression` and `FeatureChaining` inside the `OperatorExpression` for bounds that refer to a `Feature`, while the specification indicate to create a `FeatureReferenceExpression` with a referent to the `Feature`.
Note that in this second case the pilot implementation does not implement the specification, and it is not possible to have `Feature` as upper and lower bounds of a `MultiplicityRange`.
The fix is …

[1090] Fix the import of MultiplicityRange with lower and upper bounds

---

.github/workflows/build.yml
.github/workflows/doc-gen.yml
.github/workflows/generate-maven-sbom.yml
.github/workflows/generate-npm-sbom.yml

Replace template expansions ${{...}} with exporting VAR in env and using ${VAR} instead

[releng] Avoid template-injection in github workflows

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/testers/TreeItemContextMenuTester.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/SysONExplorerTreeDescriptionProvider.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/KerMLStandardLibraryDirectory.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/LibrariesDirectory.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/SysMLStandardLibraryDirectory.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/UserLibrariesDirectory.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/SysONExplorerTreeItemContextMenuEntryProvider.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/ComposedSysONExplorerService.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONDefaultExplorerService.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerFragment.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerService.java
backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerServiceDelegate.java
doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
frontend/syson/src/index.tsx

Bug: https://github.com/eclipse-syson/syson/issues/893

[893] Fix Expand All tool in SysON Explorer View

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewAddExistingElementsTestProjectData.java
backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/1398

[1398] Fix exposed Element update while d'n'd Element on General View

---

CHANGELOG.adoc
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/InterconnectionCompartmentNodeDescriptionProvider.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewFilterSwitch.java
backend/views/syson-standard-diagrams-view/src/main/java/org/eclipse/syson/standard/diagrams/view/SDVDiagramDescriptionProvider.java
doc/content/modules/user-manual/pages/release-notes/2025.10.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/1545

[1545] Add interconnection compartment on PartDefintion

---

CHANGELOG.adoc
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromDiagramTests.java
backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVPackageTests.java
backend/releng/syson-test-coverage/pom.xml
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewFilterSwitch.java
backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
doc/content/modules/user-manual/pages/release-notes/2025.10.0.adoc

Bug: https://github.com/eclipse-syson/syson/issues/1567

[1567] Fix Sub-parts are not displayed inside Package nodes
